/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
/**
 *
 * @author sahil
 */
public class CourseCard extends javax.swing.JPanel {

    /**
     * Creates new form CourseCard
     */
    private String courseName;
    private TeacherDashboard teacherDashboard;
    public CourseCard(String courseName, TeacherDashboard teacherDashboard) {
//        initComponents();
        this.courseName = courseName;
        this.teacherDashboard = teacherDashboard;

        setPreferredSize(new Dimension(300, 300));
        setBorder(BorderFactory.createLineBorder(Color.BLACK));
        setLayout(new BorderLayout());

        JLabel nameLabel = new JLabel(courseName);
        nameLabel.setHorizontalAlignment(SwingConstants.CENTER);

        JButton removeButton = new JButton("Remove");
        removeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JPanel parentPanel = (JPanel) getParent();
                parentPanel.remove(CourseCard.this);
                parentPanel.revalidate();
                parentPanel.repaint();
                return;
            }
        });

        add(nameLabel, BorderLayout.CENTER);
        add(removeButton, BorderLayout.SOUTH);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
