/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.TeacherProfileArray;

/**
 *
 * @author sahil
 */
public class TeacherProfile extends javax.swing.JPanel {

    /**
     * Creates new form TeacherProfile
     */
    private JPanel rightProcessingContainer;
    TeacherProfileArray teacherprofilearray;
    ImageIcon imageOfTeacher;   
    String teacherusername;
    public TeacherProfile(JPanel rightProcessingContainer, TeacherProfileArray teacherprofilearray, String teacherusername) {
        initComponents();
        this.rightProcessingContainer = rightProcessingContainer;
        this.teacherprofilearray = teacherprofilearray;
        this.teacherusername = teacherusername;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblTeacherPic = new javax.swing.JLabel();
        btnUploadPic = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTeacherFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTeacherEmailId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTeacherMobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTeacherAge = new javax.swing.JTextField();
        txtTeacherUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTeacherPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnTeacherFemale = new javax.swing.JRadioButton();
        btnTeacherMale = new javax.swing.JRadioButton();
        btnUpdateT1 = new javax.swing.JButton();
        btnSaveT1 = new javax.swing.JButton();

        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1400, 1080));

        lblTeacherPic.setBackground(new java.awt.Color(255, 255, 255));
        lblTeacherPic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTeacherPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeacherPic.setText("Picture");

        btnUploadPic.setBackground(new java.awt.Color(102, 255, 102));
        btnUploadPic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUploadPic.setText("Upload");
        btnUploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPicActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");

        txtTeacherFullName.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email Id");

        txtTeacherEmailId.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mobile No.");

        txtTeacherMobile.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Age");

        txtTeacherAge.setEditable(false);

        txtTeacherUsername.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        txtTeacherPassword.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Gender");

        btnTeacherFemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeacherFemale.setText("Female");
        btnTeacherFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherFemaleActionPerformed(evt);
            }
        });

        btnTeacherMale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeacherMale.setText("Male");

        btnUpdateT1.setBackground(new java.awt.Color(102, 255, 102));
        btnUpdateT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateT1.setText("Update");
        btnUpdateT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateT1ActionPerformed(evt);
            }
        });

        btnSaveT1.setBackground(new java.awt.Color(102, 255, 102));
        btnSaveT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveT1.setText("Save");
        btnSaveT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTeacherMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTeacherFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTeacherMale, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTeacherFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(203, 203, 203)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTeacherPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTeacherEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTeacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdateT1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(btnSaveT1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(279, 279, 279))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(625, 625, 625)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUploadPic, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblTeacherPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTeacherPic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadPic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTeacherFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTeacherEmailId)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTeacherMobile)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTeacherAge)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTeacherUsername)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTeacherPassword)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTeacherFemale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTeacherMale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateT1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveT1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(354, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeacherFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherFemaleActionPerformed

    private void btnUpdateT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateT1ActionPerformed
        // TODO add your handling code here:
        txtTeacherFullName.setEditable(true);
        txtTeacherEmailId.setEditable(true);
        txtTeacherMobile.setEditable(true);
        txtTeacherAge.setEditable(true);
        txtTeacherUsername.setEditable(true);
        txtTeacherPassword.setEditable(true);
        btnTeacherFemale.setEnabled(true);
        btnTeacherMale.setEnabled(true);
        
    }//GEN-LAST:event_btnUpdateT1ActionPerformed

    private void btnSaveT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveT1ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<teacherprofilearray.getTeacherProfileArray().size();i++){
            if(teacherprofilearray.getTeacherProfileArray().get(i).getUsername().equals(teacherusername)){
                teacherprofilearray.getTeacherProfileArray().get(i).setFullName(txtTeacherFullName.getText());
                teacherprofilearray.getTeacherProfileArray().get(i).setEmailId(txtTeacherEmailId.getText());
                teacherprofilearray.getTeacherProfileArray().get(i).setMobNo(txtTeacherMobile.getText());
                teacherprofilearray.getTeacherProfileArray().get(i).setAge(txtTeacherAge.getText());
                teacherprofilearray.getTeacherProfileArray().get(i).setUsername(txtTeacherUsername.getText());
                teacherprofilearray.getTeacherProfileArray().get(i).setPassword(txtTeacherPassword.getText());
                JOptionPane.showMessageDialog(this, "Profile Updated Successfully !!");
            }
        }
    }//GEN-LAST:event_btnSaveT1ActionPerformed

    private void btnUploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPicActionPerformed
        // TODO add your handling code here:
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showOpenDialog(null);
            File file=jFileChooser.getSelectedFile();

            imageOfTeacher = new ImageIcon(file.toString());
//            lblTeacherPic.setSize(150,150);
            lblTeacherPic.setIcon(imageOfTeacher);
    }//GEN-LAST:event_btnUploadPicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveT1;
    private javax.swing.JRadioButton btnTeacherFemale;
    private javax.swing.JRadioButton btnTeacherMale;
    private javax.swing.JButton btnUpdateT1;
    private javax.swing.JButton btnUploadPic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblTeacherPic;
    private javax.swing.JTextField txtTeacherAge;
    private javax.swing.JTextField txtTeacherEmailId;
    private javax.swing.JTextField txtTeacherFullName;
    private javax.swing.JTextField txtTeacherMobile;
    private javax.swing.JTextField txtTeacherPassword;
    private javax.swing.JTextField txtTeacherUsername;
    // End of variables declaration//GEN-END:variables

    private void display() {
        
        for(int i=0;i<teacherprofilearray.getTeacherProfileArray().size();i++){
            if(teacherprofilearray.getTeacherProfileArray().get(i).getUsername().equals(teacherusername)){
                txtTeacherFullName.setText(teacherprofilearray.getTeacherProfileArray().get(i).getFullName());
                txtTeacherEmailId.setText(teacherprofilearray.getTeacherProfileArray().get(i).getEmailId());
                txtTeacherMobile.setText(teacherprofilearray.getTeacherProfileArray().get(i).getMobNo());
                txtTeacherAge.setText(teacherprofilearray.getTeacherProfileArray().get(i).getAge());
                txtTeacherUsername.setText(teacherprofilearray.getTeacherProfileArray().get(i).getUsername());
                txtTeacherPassword.setText(teacherprofilearray.getTeacherProfileArray().get(i).getPassword());
                
                if(teacherprofilearray.getTeacherProfileArray().get(i).getGender().equals("Male")){
                    btnTeacherMale.setSelected(true);
                    btnTeacherFemale.setSelected(false);
                    btnTeacherFemale.setEnabled(false);
                    btnTeacherMale.setEnabled(false);
                }
                else if(teacherprofilearray.getTeacherProfileArray().get(i).getGender().equals("Female")){
                    btnTeacherFemale.setSelected(true);
                    btnTeacherMale.setSelected(false);
                    btnTeacherFemale.setEnabled(false);
                    btnTeacherMale.setEnabled(false);
                }
            }
        }
    }
}
