/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
/**
 *
 * @author sahil
 */
public class TeacherDashboard extends javax.swing.JPanel {

    /**
     * Creates new form TeacherDashboard
     */
    private JPanel coursePanel;
    private ArrayList<CourseCard> courseCards;
    public TeacherDashboard() {
        initComponents();
        setLayout(new BorderLayout());

        // Create a panel for course cards
        coursePanel = new JPanel();
        coursePanel.setLayout(new FlowLayout(FlowLayout.LEFT));
        courseCards = new ArrayList<>();

        // Create a scroll pane for course cards
        JScrollPane scrollPane = new JScrollPane(coursePanel);
        scrollPane.setPreferredSize(new Dimension(800, 600));

        // Create a button to add a new course
        JButton addCourseButton = new JButton("Add Course");
        addCourseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addNewCourseCard();
            }
        });

        // Add components to the panel
        add(scrollPane, BorderLayout.CENTER);
        add(addCourseButton, BorderLayout.SOUTH);
    }
    
    private void addNewCourseCard() {
        CourseCard courseCard = new CourseCard("New Course", this);
        courseCards.add(courseCard);
        coursePanel.add(courseCard);
        coursePanel.revalidate();
        coursePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
