/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import models.TeacherMyCoursesArray;
import models.TeacherProfileArray;

/**
 *
 * @author sahil
 */

public class TeacherLeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherLeftPanel
     */
    private JPanel rightProcessingContainer;
    private JPanel leftProcessingContainer;
    TeacherProfileArray teacherprofilearray;
    TeacherMyCoursesArray teachermycoursesarray;
    String teacherusername;
    String teacherfullname;
    public TeacherLeftPanel(JPanel rightProcessingContainer, JPanel leftProcessingContainer, TeacherProfileArray teacherprofilearray, String teacherusername, String teacherfullname, TeacherMyCoursesArray teachermycoursesarray) {
        initComponents();
        this.rightProcessingContainer = rightProcessingContainer;
        this.leftProcessingContainer = leftProcessingContainer;
        this.teacherprofilearray = teacherprofilearray;
        this.teacherusername = teacherusername;
        this.teacherfullname = teacherfullname;
        this.teachermycoursesarray = teachermycoursesarray;
        lblTeacherName.setText(teacherfullname);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPersonalInfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTeacherName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnManageMyCourses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnManageMyStudents = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnTeacherDashboard = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnTeacherLogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jPanel2.setOpaque(false);

        btnPersonalInfo.setBackground(new java.awt.Color(15, 162, 223));
        btnPersonalInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPersonalInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfo.setText("Personal Information");
        btnPersonalInfo.setBorder(null);
        btnPersonalInfo.setContentAreaFilled(false);
        btnPersonalInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPersonalInfo.setFocusTraversalPolicyProvider(true);
        btnPersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPersonalInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalInfoMouseExited(evt);
            }
        });
        btnPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile-icon-png-resized.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        kGradientPanel2.setkGradientFocus(1000);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Hello");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Welcome to WellnessWave");

        lblTeacherName.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        lblTeacherName.setForeground(new java.awt.Color(255, 255, 255));
        lblTeacherName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTeacherName.setText(".");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTeacherName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        btnManageMyCourses.setBackground(new java.awt.Color(15, 162, 223));
        btnManageMyCourses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageMyCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMyCourses.setText("Manage My Courses");
        btnManageMyCourses.setBorder(null);
        btnManageMyCourses.setContentAreaFilled(false);
        btnManageMyCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnManageMyCourses.setFocusTraversalPolicyProvider(true);
        btnManageMyCourses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageMyCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageMyCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageMyCoursesMouseExited(evt);
            }
        });
        btnManageMyCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMyCoursesActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teachermycourses.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageMyCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageMyCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel4.setOpaque(false);

        btnManageMyStudents.setBackground(new java.awt.Color(15, 162, 223));
        btnManageMyStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageMyStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMyStudents.setText("Manage My Students");
        btnManageMyStudents.setBorder(null);
        btnManageMyStudents.setContentAreaFilled(false);
        btnManageMyStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnManageMyStudents.setFocusTraversalPolicyProvider(true);
        btnManageMyStudents.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageMyStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageMyStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageMyStudentsMouseExited(evt);
            }
        });
        btnManageMyStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMyStudentsActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teachermystudent.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageMyStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageMyStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel5.setOpaque(false);

        btnTeacherDashboard.setBackground(new java.awt.Color(15, 162, 223));
        btnTeacherDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeacherDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnTeacherDashboard.setText("My Dashboard");
        btnTeacherDashboard.setBorder(null);
        btnTeacherDashboard.setContentAreaFilled(false);
        btnTeacherDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTeacherDashboard.setFocusTraversalPolicyProvider(true);
        btnTeacherDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTeacherDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTeacherDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTeacherDashboardMouseExited(evt);
            }
        });
        btnTeacherDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherDashboardActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile-icon-png-resized.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTeacherDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTeacherDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel6.setOpaque(false);

        btnTeacherLogout.setBackground(new java.awt.Color(15, 162, 223));
        btnTeacherLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeacherLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnTeacherLogout.setText("Logout");
        btnTeacherLogout.setBorder(null);
        btnTeacherLogout.setContentAreaFilled(false);
        btnTeacherLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTeacherLogout.setFocusTraversalPolicyProvider(true);
        btnTeacherLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTeacherLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTeacherLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTeacherLogoutMouseExited(evt);
            }
        });
        btnTeacherLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherLogoutActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teachermystudent.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTeacherLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTeacherLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalInfoMouseEntered
        // TODO add your handling code here:
        btnPersonalInfo.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnPersonalInfoMouseEntered

    private void btnPersonalInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalInfoMouseExited
        // TODO add your handling code here:
        btnPersonalInfo.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPersonalInfoMouseExited

    private void btnPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoActionPerformed
        // TODO add your handling code here:
        TeacherProfile teacherprofile = new TeacherProfile(rightProcessingContainer, teacherprofilearray, teacherusername);
        rightProcessingContainer.add("TeacherProfile",teacherprofile);
        CardLayout layout = (CardLayout) rightProcessingContainer.getLayout();
        layout.next(rightProcessingContainer);
    }//GEN-LAST:event_btnPersonalInfoActionPerformed

    private void btnManageMyCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMyCoursesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMyCoursesMouseEntered

    private void btnManageMyCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMyCoursesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMyCoursesMouseExited

    private void btnManageMyCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMyCoursesActionPerformed
        // TODO add your handling code here:
        TeacherManageCourses teachermanagecourses = new TeacherManageCourses(teachermycoursesarray, teacherusername);
        rightProcessingContainer.add("TeacherManageCourses",teachermanagecourses);
        CardLayout layout = (CardLayout) rightProcessingContainer.getLayout();
        layout.next(rightProcessingContainer);
    }//GEN-LAST:event_btnManageMyCoursesActionPerformed

    private void btnManageMyStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMyStudentsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMyStudentsMouseEntered

    private void btnManageMyStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMyStudentsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMyStudentsMouseExited

    private void btnManageMyStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMyStudentsActionPerformed
        // TODO add your handling code here:
        TeacherManageStudents teachermanagestudents = new TeacherManageStudents();
        rightProcessingContainer.add("TeacherManageStudents",teachermanagestudents);
        CardLayout layout = (CardLayout) rightProcessingContainer.getLayout();
        layout.next(rightProcessingContainer);
    }//GEN-LAST:event_btnManageMyStudentsActionPerformed

    private void btnTeacherDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeacherDashboardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherDashboardMouseEntered

    private void btnTeacherDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeacherDashboardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherDashboardMouseExited

    private void btnTeacherDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherDashboardActionPerformed
        // TODO add your handling code here:
        TeacherOverviewPanel1 teacherdashboard = new TeacherOverviewPanel1();
        rightProcessingContainer.add("TeacherOverviewPanel1",teacherdashboard);
        CardLayout layout = (CardLayout) rightProcessingContainer.getLayout();
        layout.next(rightProcessingContainer);
    }//GEN-LAST:event_btnTeacherDashboardActionPerformed

    private void btnTeacherLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeacherLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherLogoutMouseEntered

    private void btnTeacherLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeacherLogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherLogoutMouseExited

    private void btnTeacherLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherLogoutActionPerformed
        // TODO add your handling code here:
        leftProcessingContainer.remove(this);
        CardLayout leftlayout = (CardLayout) leftProcessingContainer.getLayout();
        leftlayout.previous(leftProcessingContainer);
        
        TeacherLoginPage teacherloginpage = new TeacherLoginPage(rightProcessingContainer, leftProcessingContainer, teacherprofilearray, teachermycoursesarray);
        rightProcessingContainer.add("TeacherLoginPage",teacherloginpage);
        CardLayout rightlayout = (CardLayout) rightProcessingContainer.getLayout();
        rightlayout.next(rightProcessingContainer);
        
    }//GEN-LAST:event_btnTeacherLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageMyCourses;
    private javax.swing.JButton btnManageMyStudents;
    private javax.swing.JButton btnPersonalInfo;
    private javax.swing.JButton btnTeacherDashboard;
    private javax.swing.JButton btnTeacherLogout;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblTeacherName;
    // End of variables declaration//GEN-END:variables
}
