/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.TeacherMyCoursesArray;
import models.TeacherProfileArray;

/**
 *
 * @author sahil
 */
public class TeacherLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form TeacherLoginPage
     */
    JPanel rightProcessingContainer;
    JPanel leftProcessingContainer;
    TeacherProfileArray teacherprofilearray;
    TeacherMyCoursesArray teachermycoursesarray;
    TeacherProfile teacherprofile;
    
    public TeacherLoginPage(JPanel rightProcessingContainer, JPanel leftProcessingContainer,TeacherProfileArray teacherprofilearray, TeacherMyCoursesArray teachermycoursesarray) {
        initComponents();
        this.rightProcessingContainer = rightProcessingContainer;
        this.leftProcessingContainer = leftProcessingContainer;
        this.teacherprofilearray = teacherprofilearray;
        this.teachermycoursesarray = teachermycoursesarray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTeacherUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTeacherPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTeacherLogin = new models.MyButton();
        btnTeacherSignUp = new models.MyButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1400, 1080));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher Login");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't have an account?");

        btnTeacherLogin.setBackground(new java.awt.Color(153, 255, 102));
        btnTeacherLogin.setText("Login");
        btnTeacherLogin.setBorderColor(new java.awt.Color(153, 255, 102));
        btnTeacherLogin.setColor(new java.awt.Color(153, 255, 102));
        btnTeacherLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeacherLogin.setRadius(10);
        btnTeacherLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherLoginActionPerformed(evt);
            }
        });

        btnTeacherSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnTeacherSignUp.setText("Sign Up");
        btnTeacherSignUp.setBorderColor(new java.awt.Color(51, 51, 255));
        btnTeacherSignUp.setColor(new java.awt.Color(51, 51, 255));
        btnTeacherSignUp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnTeacherSignUp.setRadius(10);
        btnTeacherSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(btnTeacherSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(txtTeacherUsername))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTeacherPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnTeacherLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeacherPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btnTeacherLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTeacherSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(566, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeacherSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherSignUpActionPerformed
        // TODO add your handling code here:
        TeacherSignUp teachersignup = new TeacherSignUp(rightProcessingContainer, leftProcessingContainer,teacherprofilearray, teachermycoursesarray);
        rightProcessingContainer.add("TeacherSignUp",teachersignup);
        CardLayout layout = (CardLayout) rightProcessingContainer.getLayout();
        layout.next(rightProcessingContainer);
    }//GEN-LAST:event_btnTeacherSignUpActionPerformed

    private void btnTeacherLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherLoginActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<teacherprofilearray.getTeacherProfileArray().size();i++){
            if(txtTeacherUsername.getText().equals(teacherprofilearray.getTeacherProfileArray().get(i).getUsername())
                    && txtTeacherPassword.getText().equals(teacherprofilearray.getTeacherProfileArray().get(i).getPassword())){
                
                String teacherusername = teacherprofilearray.getTeacherProfileArray().get(i).getUsername();
                String teacherfullname = teacherprofilearray.getTeacherProfileArray().get(i).getFullName();
                
                TeacherLeftPanel teacherleftpanel = new TeacherLeftPanel(rightProcessingContainer, leftProcessingContainer,teacherprofilearray, teacherusername,teacherfullname, teachermycoursesarray);
                leftProcessingContainer.add("TeacherLeftPanel",teacherleftpanel);
                CardLayout layout = (CardLayout) leftProcessingContainer.getLayout();
                layout.next(leftProcessingContainer);
                
                TeacherOverviewPanel1 teacheroverviewpanel1 = new TeacherOverviewPanel1();
                rightProcessingContainer.add("TeacherOverviewPanel1",teacheroverviewpanel1);
                CardLayout layout2 = (CardLayout) rightProcessingContainer.getLayout();
                layout2.next(rightProcessingContainer);
                
                JOptionPane.showMessageDialog(this, "Teacher Login Successfull !!");
            }
        }
    }//GEN-LAST:event_btnTeacherLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private models.MyButton btnTeacherLogin;
    private models.MyButton btnTeacherSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtTeacherPassword;
    private javax.swing.JTextField txtTeacherUsername;
    // End of variables declaration//GEN-END:variables
}
