/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.TeacherMyCourses;
import models.TeacherMyCoursesArray;

/**
 *
 * @author sahil
 */
public class TeacherAddCourses1 extends javax.swing.JPanel {

    /**
     * Creates new form TeacherUpdateCourses1
     */
    TeacherMyCoursesArray teachermycoursesarray;
    String teacherusername;
    ImageIcon imageOfMyCourse;
    public TeacherAddCourses1(TeacherMyCoursesArray teachermycoursesarray, String teacherusername) {
        initComponents();
        System.out.println("Inside TeacherAddCourses1");
        this.teachermycoursesarray = teachermycoursesarray;
        this.teacherusername = teacherusername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtCoursePriceT2_2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dropdownSemester = new javax.swing.JComboBox<>();
        dropdownSubject = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCourseNameT2_2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMyCoursePic = new javax.swing.JLabel();
        btnUploadPicT2_2 = new javax.swing.JButton();
        jCheckBoxMonday = new javax.swing.JCheckBox();
        jCheckBoxTuesday = new javax.swing.JCheckBox();
        jCheckBoxWednesday = new javax.swing.JCheckBox();
        jCheckBoxThursday = new javax.swing.JCheckBox();
        jCheckBoxFriday = new javax.swing.JCheckBox();
        jCheckBoxSaturday = new javax.swing.JCheckBox();
        jCheckBoxSunday = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCourseCatalogT2_2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAddCourseT2_2 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Course Price");

        dropdownSemester.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dropdownSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropdownSubject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dropdownSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Computers", "Maths", "Physics", "English", "Biology", "History", "Architecture", "Arts", "Dance", "Music" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Select Subject");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Select Semester");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Course Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Course Image");

        lblMyCoursePic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMyCoursePic.setText("Picture...");

        btnUploadPicT2_2.setBackground(new java.awt.Color(153, 255, 102));
        btnUploadPicT2_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUploadPicT2_2.setText("Upload");
        btnUploadPicT2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPicT2_2ActionPerformed(evt);
            }
        });

        jCheckBoxMonday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxMonday.setText("Monday");

        jCheckBoxTuesday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxTuesday.setText("Tuesday");

        jCheckBoxWednesday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxWednesday.setText("Wednesday");

        jCheckBoxThursday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxThursday.setText("Thursday");

        jCheckBoxFriday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxFriday.setText("Friday");

        jCheckBoxSaturday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxSaturday.setText("Saturday");

        jCheckBoxSunday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxSunday.setText("Sunday");
        jCheckBoxSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSundayActionPerformed(evt);
            }
        });

        txtCourseCatalogT2_2.setColumns(20);
        txtCourseCatalogT2_2.setRows(5);
        jScrollPane2.setViewportView(txtCourseCatalogT2_2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Course Catalog");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Course Days");

        btnAddCourseT2_2.setBackground(new java.awt.Color(153, 255, 102));
        btnAddCourseT2_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCourseT2_2.setText("Add Course");
        btnAddCourseT2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseT2_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dropdownSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dropdownSemester, 0, 150, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCourseNameT2_2)
                                            .addComponent(btnUploadPicT2_2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(lblMyCoursePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCoursePriceT2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBoxMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxSaturday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCourseT2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dropdownSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dropdownSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCourseNameT2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCoursePriceT2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMyCoursePic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnUploadPicT2_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxMonday)
                    .addComponent(jCheckBoxTuesday)
                    .addComponent(jCheckBoxWednesday)
                    .addComponent(jCheckBoxThursday)
                    .addComponent(jCheckBoxFriday)
                    .addComponent(jCheckBoxSaturday)
                    .addComponent(jCheckBoxSunday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddCourseT2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1298, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 874, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSundayActionPerformed

    private void btnAddCourseT2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseT2_2ActionPerformed
        // TODO add your handling code here:
        String[] CourseSchedule = new String[7];
        if(teachermycoursesarray.getTeacherMyCoursesArray().isEmpty()){
            TeacherMyCourses teachermycourses = teachermycoursesarray.addNewMyCourse();
            teachermycourses.setTeacherUsername(teacherusername);
            teachermycourses.setCourseSubject(dropdownSubject.getSelectedItem().toString());
            teachermycourses.setCourseSemester(dropdownSemester.getSelectedItem().toString());
            teachermycourses.setCourseName(txtCourseNameT2_2.getText());
            teachermycourses.setCoursePrice(txtCoursePriceT2_2.getText());
            teachermycourses.setCatalog(txtCourseCatalogT2_2.getText());
            teachermycourses.setImageOfCourse(imageOfMyCourse);
            
                if(jCheckBoxMonday.isSelected()){
                    CourseSchedule[0] = "Monday";
                }
                else if(!jCheckBoxMonday.isSelected()){
                    CourseSchedule[0] = "";
                }
                
                if(jCheckBoxTuesday.isSelected()){
                    CourseSchedule[1] = "Tuesday";
                }
                else if(!jCheckBoxTuesday.isSelected()){
                    CourseSchedule[1] = "";
                }
                
                if(jCheckBoxTuesday.isSelected()){
                    CourseSchedule[2] = "Wednesday";
                }
                else if(!jCheckBoxTuesday.isSelected()){
                    CourseSchedule[2] = "";
                }
                
                if(jCheckBoxThursday.isSelected()){
                    CourseSchedule[3] = "Thursday";
                }
                else if(!jCheckBoxThursday.isSelected()){
                    CourseSchedule[3] = "";
                }
                
                if(jCheckBoxFriday.isSelected()){
                    CourseSchedule[4] = "Friday";
                }
                else if(!jCheckBoxFriday.isSelected()){
                    CourseSchedule[4] = "";
                }
                
                if(jCheckBoxSaturday.isSelected()){
                    CourseSchedule[5] = "Saturday";
                }
                else if(!jCheckBoxSaturday.isSelected()){
                    CourseSchedule[5] = "";
                }
                
                if(jCheckBoxSunday.isSelected()){
                    CourseSchedule[6] = "Sunday";
                }
                else if(!jCheckBoxSunday.isSelected()){
                    CourseSchedule[6] = "";
                }
                
                for (String CourseSchedule1 : CourseSchedule) {
                    System.out.println("Course array - " + CourseSchedule1);
                }
                teachermycourses.setCourseSchedule(CourseSchedule.clone());
                JOptionPane.showMessageDialog(this, "New Course Created Successfully !!");
        }
        else if(!teachermycoursesarray.getTeacherMyCoursesArray().isEmpty()){
            for(int i=0;i<teachermycoursesarray.getTeacherMyCoursesArray().size();i++){
                System.out.println("Inside TeacherAdd Courses for loop - Btn clicked");
                if(teachermycoursesarray.getTeacherMyCoursesArray().get(i).getTeacherUsername().equals(teacherusername)){
                    System.out.println("Adding new course - If loop");
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setTeacherUsername(teacherusername);
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setCourseSubject(dropdownSubject.getSelectedItem().toString());
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setCourseSemester(dropdownSemester.getSelectedItem().toString());
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setCourseName(txtCourseNameT2_2.getText());
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setCoursePrice(txtCoursePriceT2_2.getText());
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setCatalog(txtCourseCatalogT2_2.getText());
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setImageOfCourse(imageOfMyCourse);
                    
                    if(jCheckBoxMonday.isSelected()){
                        CourseSchedule[0] = "Monday";
                    }
                    else if(!jCheckBoxMonday.isSelected()){
                        CourseSchedule[0] = "";
                    }

                    if(jCheckBoxTuesday.isSelected()){
                        CourseSchedule[1] = "Tuesday";
                    }
                    else if(!jCheckBoxTuesday.isSelected()){
                        CourseSchedule[1] = "";
                    }

                    if(jCheckBoxTuesday.isSelected()){
                        CourseSchedule[2] = "Wednesday";
                    }
                    else if(!jCheckBoxTuesday.isSelected()){
                        CourseSchedule[2] = "";
                    }

                    if(jCheckBoxThursday.isSelected()){
                        CourseSchedule[3] = "Thursday";
                    }
                    else if(!jCheckBoxThursday.isSelected()){
                        CourseSchedule[3] = "";
                    }

                    if(jCheckBoxFriday.isSelected()){
                        CourseSchedule[4] = "Friday";
                    }
                    else if(!jCheckBoxFriday.isSelected()){
                        CourseSchedule[4] = "";
                    }

                    if(jCheckBoxSaturday.isSelected()){
                        CourseSchedule[5] = "Saturday";
                    }
                    else if(!jCheckBoxSaturday.isSelected()){
                        CourseSchedule[5] = "";
                    }

                    if(jCheckBoxSunday.isSelected()){
                        CourseSchedule[6] = "Sunday";
                    }
                    else if(!jCheckBoxSunday.isSelected()){
                        CourseSchedule[6] = "";
                    }

                    for (String CourseSchedule1 : CourseSchedule) {
                        System.out.println("Course array - " + CourseSchedule1);
                    }
                    teachermycoursesarray.getTeacherMyCoursesArray().get(i).setCourseSchedule(CourseSchedule.clone());
                    JOptionPane.showMessageDialog(this, "New Course Created Successfully !!");

                }
            }
        }
    }//GEN-LAST:event_btnAddCourseT2_2ActionPerformed

    private void btnUploadPicT2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPicT2_2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file=jFileChooser.getSelectedFile();
        imageOfMyCourse = new ImageIcon(file.toString());
        lblMyCoursePic.setSize(200,100);
        lblMyCoursePic.setIcon(imageOfMyCourse);
    }//GEN-LAST:event_btnUploadPicT2_2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourseT2_2;
    private javax.swing.JButton btnUploadPicT2_2;
    private javax.swing.JComboBox<String> dropdownSemester;
    private javax.swing.JComboBox<String> dropdownSubject;
    private javax.swing.JCheckBox jCheckBoxFriday;
    private javax.swing.JCheckBox jCheckBoxMonday;
    private javax.swing.JCheckBox jCheckBoxSaturday;
    private javax.swing.JCheckBox jCheckBoxSunday;
    private javax.swing.JCheckBox jCheckBoxThursday;
    private javax.swing.JCheckBox jCheckBoxTuesday;
    private javax.swing.JCheckBox jCheckBoxWednesday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblMyCoursePic;
    private javax.swing.JTextArea txtCourseCatalogT2_2;
    private javax.swing.JTextField txtCourseNameT2_2;
    private javax.swing.JTextField txtCoursePriceT2_2;
    // End of variables declaration//GEN-END:variables
}
